name: MinecraftSurvival
version: ${project.version}
main: de.thomas.minecraftsurvival.MinecraftSurvival
api-version: 1.17
authors: [ Thomas ]
description: Ein Plugin für das Survival Projekt
load: POSTWORLD
commands:
  ping:
    description: Gibt den Ping zum Server an
