name: Cleanup Artifacts

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  Remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '1 days'
          skip-tags: false
          skip-recent: 1